[Server]
    wit_host = "api.wit.ai"
    wit_port = 443
    wit_API = "USPKTAOSA557WRC6CKHQW6BZVSVLID6W"
    rasa_host = "localhost"
    rasa_port = 5005
    rasa_API = "token"
    tmdb_host = "api.themoviedb.org"
    tmdb_port = 443
    tmdb_API = "c038a92e3fe9346f02feaf2d8ae2efab"
    self_host = "localhost"
    self_port = 8080