# here place the host names, ports and API keys for the different services (rasa, asr, tts.ai, etc.)
[server]
    tts_host = "localhost"
    tts_port = 8082
    tts_API = ""
    tts_SSL = false

    rasa_host = "localhost"
    rasa_port = 5005
    rasa_API = ""
    rasa_SSL = false

    self_host = "localhost"
    self_port = 8080
    self_API = ""
    self_SSL = false

    asr_host = "localhost"
    asr_port = 8081
    asr_API = ""
    asr_SSL = false