# here place the host names, ports and API keys for the different services (rasa, asr, wit.ai, etc.)
[server]
    wit_host = "api.wit.ai"
    wit_port = 443
    wit_API = "USPKTAOSA557WRC6CKHQW6BZVSVLID6W"
    wit_SSL = true

    rasa_host = "localhost"
    rasa_port = 5005
    rasa_API = ""
    rasa_SSL = false

    self_host = "localhost"
    self_port = 8080
    self_API = ""
    self_SSL = false

    asr_host = "localhost"
    asr_port = 8081
    asr_API = ""
    asr_SSL = false