# here place the host names, ports and API keys for the different services (rasa_actions, asr, tts.ai, etc.)
[server]

    self_host = "localhost"
    self_port = 8080
    self_API = ""
    self_SSL = false

    asr_host = "localhost"
    asr_port = 8081
    asr_API = ""
    asr_SSL = false
    autostart_asr = true # if true the main process will start an asr server
    asr_path = "src/asr/asr_server.py" # path to the asr server
    asr_args = "" # arguments to pass to the asr server
    
    tts_host = "localhost"
    tts_port = 8082
    tts_API = ""
    tts_SSL = false
    autostart_tts = true # if true the main process will start a tts server
    tts_path = "src/tts/tts_server.py" # path to the tts server
    tts_args = "" # arguments to pass to the tts server

[[bots]]
    name = "movie_bot"
    rasa_host = "localhost"
    rasa_port = 5004
    rasa_API = ""
    rasa_SSL = false
    speaker_voice = "clb" # voice to use for the rasa server. By deafault bdl, slt, jmk, awb, rms, clb, ksp are available

[[bots]]
    name = "triage_bot"
    rasa_host = "localhost"
    rasa_port = 5005
    rasa_API = ""
    rasa_SSL = false
    speaker_voice = "slt" # voice to use for the rasa server. By deafault bdl, slt, jmk, awb, rms, clb, ksp are available
[[bots]]
    name = "anamnesis_bot"
    rasa_host = "localhost"
    rasa_port = 5006
    rasa_API = ""
    rasa_SSL = false
    speaker_voice = "bdl" # voice to use for the rasa server. By deafault bdl, slt, jmk, awb, rms, clb, ksp are available
[[bots]]
    name = "operation_bot"
    rasa_host = "localhost"
    rasa_port = 5007
    rasa_API = ""
    rasa_SSL = false
    speaker_voice = "clb" # voice to use for the rasa server. By deafault bdl, slt, jmk, awb, rms, clb, ksp are available

[settings]
timeout = 10 # timeout for the server to respond